name: Build & Deploy
on:
  push:
    branches: 
    - master


jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn install
    - run: yarn build
  
    - uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
     
        script: |

          cd /var/tmp


