name: Build & Deploy
on:
  push:
    branches: 
    - master


jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        path: dist
    - run: yarn install
    - run: yarn build
  
    - uses: garygrossgarten/github-action-scp@release
      with:
        local: my-repo
        remote: /var/tmp
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
